### ISSUE TITLE
Mailchimp API Key undefined

### ISSUE THREAD

**Issue by jdjuan** [angular-medellin/backend#3]
Hey @alejandronanez I get this error when I run `yarn start`. 
I have updated `MAILCHIMP_KEY=123456` with the MailChimp API Key.

![image](https://user-images.githubusercontent.com/3171900/27811288-3bd05454-602a-11e7-8107-183d24c72f72.png)

If it is currently working on your Mac then it might be a Windows issue. Any idea?

PS: I also logged `process.env` and I got my env variables but no `MAILCHIMP_KEY`

**Comment by alejandronanez** [comment]
Did you create the `.env` file with the right env variable? There should not be problem with windows because we're using the `dotenv` npm module.

**Comment by jdjuan** [comment]
There was already a file called `.env.template`. Thought it was the file I was supposed to update 😁 so what should be actual name? Just `.env` inside `src`?

Think we can leave it there with dummy credentials, and then we can gitignore it

**Comment by alejandronanez** [comment]
So basically `.env.sample` is just a _template_, you should rename it to `.env` and update the MailChimp credentials accordingly.
`.env` is already _gitignored_ this is a good practice  because you don't want your real credentials in  any of your commit history.

**Comment by jdjuan** [comment]
Perfect! It's working! Quite easy to use the MailChimp API right? 😁

**Comment by alejandronanez** [comment]
Indeed, easy peasy lemon squeezy 👌🏼
